POST http://127.0.0.1:6880/api/user/login/account
Content-Type: application/json

{
  "userName": "李先宏",
  "password": "123456"
}
###
POST http://127.0.0.1:6880/api/user/login/account
Content-Type: application/json

{
  "userName": "李先宏",
  "password": "1234567"
}
###
GET http://127.0.0.1:6880/api/user